# Generated by Django 3.2 on 2021-06-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210621_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ProjectLink',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='RepositoryLink',
            field=models.URLField(blank=True),
        ),
    ]
