# Generated by Django 3.2 on 2021-06-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='DisplayImage',
            new_name='LargeImage',
        ),
        migrations.AddField(
            model_name='project',
            name='MobileImage',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
