export { default as Nav } from './nav';
export { default as BackGround } from './background';
export { default as Main } from './main';
export { default as Skills } from './skills';
export { default as Bar } from './bar';
export { default as Portfolio } from './portfolio';
export { default as About } from './about';
export { default as Resume } from './resume';
export { default as Contact } from './contact';